apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: print-slate-wasm-plugin
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin
  url: oci://ghcr.io/adiprerepa/print-slate-plugin:latest 