  apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: slate-wasm-plugin
  namespace: default
spec:
  selector:
    matchLabels:
      app: ratings
  url: oci://ghcr.io/adiprerepa/slate-plugin:latest 